# Generated by Django 4.2 on 2024-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Описание")),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_published", "Не опубликовано"),
                            ("moderation", "На модерации"),
                            ("published", "Опубликовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="no_published",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/diary/images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "Запись в дневнике",
                "verbose_name_plural": "Записи в дневнике",
                "ordering": ["-created_at"],
                "permissions": [("can_moderate", "Может модерировать записи")],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Тема сообщения",
                    ),
                ),
                ("body", models.TextField(verbose_name="Сообщение")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Прочитано"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["is_read", "-created"],
            },
        ),
    ]
