# Generated by Django 4.2 on 2024-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Опубликовано"),
                    ("no_published", "Не опубликовано"),
                    ("moderation", "На модерации"),
                    ("rejected", "Отклонено"),
                ],
                default="no_published",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
